name: Deploy to Prd

on:
  push:
    branches:
      - main

jobs:
  deploy-prd:
    environment: prd
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GitHub context
        run: |
          echo "repository        = ${{ github.repository }}"
          echo "repository_owner  = ${{ github.repository_owner }}"
          echo "ref               = ${{ github.ref }}"
          echo "ref_name          = ${{ github.ref_name }}"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        run: |
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}

      - name: Build and Push Docker Image (Prd)
        run: |
          docker build --platform linux/arm64 -t ${{ vars.ACR_LOGIN_SERVER }}/sample-app:prd .

      - name: Deploy to Prd Namespace
        run: |
          sed -e "s|IMAGE_NAME|${{ vars.ACR_LOGIN_SERVER }}/sample-app:prd|g" \
              -e "s|ENV_VALUE|${{ vars.PRD_ENV }}|g" \
              K8s/deployment.yml | kubectl apply -n prd -f -

          kubectl apply -n prd -f K8s/service.yml